export const logos: string[] = [
  'assets/ClientLogos/image-1.svg',
  'assets/ClientLogos/image-3.svg',
  'assets/ClientLogos/image-2.svg',
  'assets/ClientLogos/image-4.svg',
  'assets/ClientLogos/image-5.svg',
  'assets/ClientLogos/image-6.svg',
  'assets/ClientLogos/image-7.svg',
  'assets/ClientLogos/image-8.svg',
  'assets/ClientLogos/image-9.svg',
  'assets/ClientLogos/image-10.svg',
  'assets/ClientLogos/image-11.svg',
  'assets/ClientLogos/image-12.svg',
  'assets/ClientLogos/image-13.svg',
  'assets/ClientLogos/image-14.svg',
  'assets/ClientLogos/image-15.svg',
  'assets/ClientLogos/image-16.svg',
  'assets/ClientLogos/image-17.svg',
  'assets/ClientLogos/image-18.svg',
  'assets/ClientLogos/image-19.svg',
  'assets/ClientLogos/image-20.svg',
  'assets/ClientLogos/image-21.svg',
  // 'assets/ClientLogos/image-22.svg',
  'assets/ClientLogos/image-23.svg',
  'assets/ClientLogos/image-24.svg',
];